language: php

php:
  - 7.0
  - 7.1

before_script:
  - cp .env.travis .env
  - mysql -e 'create database tests;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --database tests
  - mkdir -p build/logs

script:
  - php vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v